# Assumes all service accounts have root access
#   Configure via: `kubectl create clusterrolebinding serviceaccounts-cluster-admin --clusterrole=cluster-admin --group=system:serviceaccounts`
#
# After applying run `kubectl get secret/gha-secret -n pt -o yaml` and copy the result into
#   the GitHub secret K8S_SECRET
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gha
  namespace: pt
---
apiVersion: v1
kind: Secret
metadata:
  name: gha-secret
  namespace: pt
  annotations:
    kubernetes.io/service-account.name: gha
type: kubernetes.io/service-account-token
