name: Deploy
on:
  push:
    branches: [main]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v4

      - uses: docker/build-push-action@v3
        name: Build and push the docker image
        with:
          platforms: linux/arm64
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - uses: azure/k8s-set-context@v1
        with:
          method: service-account
          k8s-url: "https://stork:6443"
          k8s-secret: ${{ secrets.K8S_SECRET }}
        id: setcontext

      - uses: actions/checkout@v4

      - name: Deploy to k8s
        uses: azure/k8s-deploy@v5
        with:
          namespace: pt
          manifests: ./infra
          images: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}
